#' Plot Comparison of Model Specifications
#'
#' @description
#' Generates a comprehensive 2x2 diagnostic dashboard comparing models with and
#' without an intercept. This visualization helps identify how the absence of
#' an intercept affects different R-squared definitions and error metrics.
#'
#' @details
#' The plot is organized into four panels:
#' \itemize{
#'   \item **Top-Left**: Grouped bar chart of the nine R-squared definitions.
#'   \item **Bottom-Left**: Comparison of absolute fit metrics (RMSE, MAE, MSE).
#'   \item **Top-Right**: Observed vs. Predicted plot for the intercept model.
#'   \item **Bottom-Right**: Observed vs. Predicted plot for the no-intercept model.
#' }
#' This layout allows for a direct "cause-and-effect" analysis: for instance,
#' observing a data point far from the identity line in the bottom-right panel
#' explains why certain R-squared definitions might crash or become negative
#' in the left panels.
#'
#' @param x An object of class `comp_model` generated by [comp_model()].
#' @param ... Further graphical parameters (currently ignored).
#'
#' @return
#' This function is primarily called for its side effect of creating a
#' \code{grid}-based plot. It returns the input object \code{x} invisibly.
#'
#' @note
#' Since this plot uses the `grid` system to combine multiple `ggplot`
#' objects, it cannot be further modified with the `+` operator. If you
#' need to customize individual panels, use the internal plotting functions
#' or extract the models from the `comp_model` object attributes.
#'
#' @seealso [comp_model()], [plot_diagnostic()]
#' @examples
#' \dontrun{
#' df <- data.frame(x = 1:5, y = c(2, 3, 5, 4, 6))
#' m1 <- lm(y ~ x)
#' res <- comp_model(m1)
#' plot(res)
#' }
#'
#' @importFrom ggplot2 .data
#' @export
plot.comp_model <- function(x, ...) {

  p_r2 <- .plot_comp_r2(x)

  p_fit <- .plot_comp_fit(x)

  p_diag_with <- plot_diagnostic(attr(x, "with_int")) +
    ggplot2::labs(subtitle = "With Intercept")
  p_diag_without <- plot_diagnostic(attr(x, "without_int")) +
    ggplot2::labs(subtitle = "Without Intercept")


  grid::grid.newpage()
  grid::pushViewport(grid::viewport(layout = grid::grid.layout(2, 2, widths = grid::unit(c(1.2, 1), "null"))))

  print(p_r2,   vp = grid::viewport(layout.pos.row = 1, layout.pos.col = 1))
  print(p_fit,  vp = grid::viewport(layout.pos.row = 2, layout.pos.col = 1))

  print(p_diag_with, vp = grid::viewport(layout.pos.row = 1, layout.pos.col = 2))
  print(p_diag_without,  vp = grid::viewport(layout.pos.row = 2, layout.pos.col = 2))

  invisible(x)
}

.plot_comp_r2 <- function(x) {
  df_r2 <- tidyr::pivot_longer(as.data.frame(x),
                               cols = 2:10,
                               names_to = "Definition",
                               values_to = "Value")
  df_r2$Definition <- factor(df_r2$Definition, levels = unique(df_r2$Definition))
  df_r2$Status <- ifelse(df_r2$Value < 0 | df_r2$Value > 1, "Warning", "Normal")


  ggplot2::ggplot(df_r2, ggplot2::aes(x = .data$Definition, y = .data$Value, fill = .data$model)) +
    ggplot2::geom_col(position = ggplot2::position_dodge(width = 0.8)) +
    ggplot2::geom_hline(yintercept = 1, color = "blue", linetype = "dashed", linewidth = 0.8) +
    ggplot2::geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 0.8) +    ggplot2::scale_fill_manual(values = c("with intercept" = "skyblue", "without intercept" = "lightcoral")) +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "R-squared Definitions: Intercept vs. No-Intercept",
                  x = NULL, y = "R-squared Value", fill = "Model Type",
                  caption = if(any(df_r2$Status == "Warning")) "Note: Orange bars indicate values outside [0, 1] range." else NULL
    ) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))
}

.plot_comp_fit <- function(x) {
  df_fit <- tidyr::pivot_longer(as.data.frame(x),
                                cols = 11:13,
                                names_to = "Metric",
                                values_to = "Value")
  df_fit$Metric <- toupper(df_fit$Metric)

  ggplot2::ggplot(df_fit, ggplot2::aes(x = .data$Metric, y = .data$Value, fill = .data$model)) +
    ggplot2::geom_col(position = ggplot2::position_dodge(width = 0.8)) +
    ggplot2::scale_fill_manual(values = c("with intercept" = "skyblue", "without intercept" = "lightcoral")) +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "Fit Metrics (Error scales)",
                  x = NULL, y = "Absolute Error", fill = "Model Type")
}
