#' Print Methods for r2 and comp_fit calculation Objects
#' @description
#' Printing objects of class "`r2_kvr2`" (generated by `r2`) or "`comp_kvr2`" (generated by `comp_fit`), respectively, by simple print methods.
#'
#' @param x AN object of class "`r2_kvr2`" or "`comp_kvr2`".
#' @param digits The number of significant digits to be used for printing.
#'   Default to 4.
#' @param ... Further arguments passed to or from other methods.
#'
#' @details
#' These methods format the calculated statistics into a human-readable
#' summary, displaying each index or metric with its corresponding value.
#'
#' @seealso [r2] [comp_fit] [r2_adjusted]
#'
#' @rdname print.kvr2
#'
#' @export
print.r2_kvr2 <- function(x, ..., digits = 4){
  stopifnot(class(x) == "r2_kvr2")

  # if(!is.null(x$r2_1)) cat(chartr("r", "R", names(x$r2_1)), ": ", format(round(x$r2_1, digits = digits), nsmall = digits), "\n")
  # if(!is.null(x$r2_2)) cat(chartr("r", "R", names(x$r2_2)), ": ", format(round(x$r2_2, digits = digits), nsmall = digits), "\n")
  # if(!is.null(x$r2_3)) cat(chartr("r", "R", names(x$r2_3)), ": ", format(round(x$r2_3, digits = digits), nsmall = digits), "\n")
  # if(!is.null(x$r2_4)) cat(chartr("r", "R", names(x$r2_4)), ": ", format(round(x$r2_4, digits = digits), nsmall = digits), "\n")
  # if(!is.null(x$r2_5)) cat(chartr("r", "R", names(x$r2_5)), ": ", format(round(x$r2_5, digits = digits), nsmall = digits), "\n")
  # if(!is.null(x$r2_6)) cat(chartr("r", "R", names(x$r2_6)), ": ", format(round(x$r2_6, digits = digits), nsmall = digits), "\n")
  # if(!is.null(x$r2_7)) cat(chartr("r", "R", names(x$r2_7)), ": ", format(round(x$r2_7, digits = digits), nsmall = digits), "\n")
  # if(!is.null(x$r2_8)) cat(chartr("r", "R", names(x$r2_8)), ": ", format(round(x$r2_8, digits = digits), nsmall = digits), "\n")
  # if(!is.null(x$r2_9)) cat(chartr("r", "R", names(x$r2_9)), ": ", format(round(x$r2_9, digits = digits), nsmall = digits), "\n")
  sapply(x, function(x){
    cat(chartr("r", "R", names(x)), ": ", format(round(x, digits = digits), nsmall = digits), "\n")
  })
}

#' @rdname print.kvr2
#' @export
print.comp_kvr2 <- function(x, ..., digits = 4){
  stopifnot(class(x) == "comp_kvr2")


  # if(x$rmse) cat("RMSE: ", format(round(x$rmse, digits = digits), nsmall = digits), "\n")
  # if(!is.null(x$rmse) cat(" ")
  # if(x$mae) cat("MAE: ",  format(round(x$mae,  digits = digits), nsmall = digits), "\n")
  # if(x$mse) cat("MSE: ",  format(round(x$mse,  digits = digits), nsmall = digits), "\n")

  sapply(x, function(x){
    cat(names(x), ": ", format(round(x,  digits = digits), nsmall = digits), "\n")
  })
}
